name: Configure pulumi
description: Configure pulumi
runs:
  using: node16
  main: dist/index.js
inputs:
  revision:
    description: git revision
    required: true
  bucket:
    description: name of s3 bucket where image tag names are stored
    default: drifti-build
    required: false
outputs:
  config:
    description: pulumi config params
