name: Configure pulumi
description: Configure pulumi
runs:
  using: node12
  main: index.js
inputs:
  stackName:
    description: name of pulumi stack to configure
    required: true
  revision:
    description: git revision
    required: true
  bucket:
    description: name of s3 bucket where image tag names are stored
    default: pronto-build
    required: false
outputs:
  config:
    description: pulumi config params
